Jbnahan\MyAppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        jbnahanAccessToken:
            type: string
            length: 255
            nullable: true
        jbnahanId:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }

