parameters:
#    jbnahan_my_app.example.class: Jbnahan\MyAppBundle\Example
    jbnahan_my_app.user_provider.class: Jbnahan\MyAppBundle\Security\JbnahanUserProvider

services:
#    jbnahan_my_app.example:
#        class: %jbnahan_my_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    jbnahan_my_app.user_provider:
        class: %jbnahan_my_app.user_provider.class%
        arguments: ["@fos_user.user_manager", { jbnahan_custom: jbnahanId }]